### ISSUE TITLE
Update to latest version of llvm/circt firtool

### ISSUE THREAD

**Issue by pepper-lees** [ucb-bar/firtool-feedstock#5]
Hi,

There have been some bug fixes since the last version of firtool that was released on the Anaconda repo, which I need for Chipyard. Can you update firtool on Anaconda to 1.45.0? Or, better yet, is there a way to migrate the Anaconda publishing logic (which I assume is what this repo is for) to https://github.com/llvm/circt, so that they can automatically update the published package whenever they release a new version of firtool?

Thanks!

**Comment by abejgonzalez** [comment]
Sorry, I didn't get the notification for this. Next time feel free to ping me or create a pull request with the bump.

**Comment by abejgonzalez** [comment]
I just pushed a bump to 1.58.0 onto the master branch. It should be ready by EOD
